### ISSUE TITLE
Is their a mechanism for hostvars?

### ISSUE THREAD

**Issue by rhugga** [apenella/go-ansible#66]
Im building my inventory dynamically, but I want to use host variables, ie assume the following traditional inventory:

Can this library implement host variables that would have the same effect as this inventory file?
```
all:
  vars:
    new_kernel_version: kernel-3.10.0-1160.36.2.el7.x86_64
  children:
    cluster:
      hosts:
        host1:
          ansible_host: host1.example.com
          rack: rack1
          platform: xyz
```
